### ISSUE TITLE
Problems trying to make the extension work

### ISSUE THREAD

**Issue by ferrandusqui31** [Ardethian/localhost_automate#2]
Hello. I downloaded the extension to try to localhost a project. I am putting in the extension in the part of "Localhost directory" the full URL that puts in chrome when I open the html file locally and in the localhost URL part "http://localhost:1009". After saving that i go to the localhost URL in chrome but I have the error which refers to that a website doesn't exist.
Do you know what I am doing wrong?
Thanks

**Comment by dewbjorn** [comment]
Hi @ferrandusqui31, thanks for taking the time to write this.

What this extension does is map a file path on your machine to an existing localhost server path, meaning that, for example, if you open a file located in `d:\xampp\htdocs\index.html` in Chrome and get a path like `file://d:/xampp/htdocs/index.html`, you'd get redirected to `localhost:1009/index.html` (with respective ports and routing of course).

Do you have an actual localhost server running in the background?

**Comment by ferrandusqui31** [comment]
Thanks for helping me. This still haven't solved this but let me explain if I have understood well.

When you open the extension, in the localhost directory field you put the local path of your file. Ej: `d:\xampp\htdocs\index.html`. Then in the localhost URL field you put the localhost URL where will be runned the file. Ej: `localhost:1009`. And this makes that when you open in chrome the file from the first field i will be openned in the localhost (`localhost:1009/index.html`) directly, no? If it's like that probably we can't do anything alse because of chromeos.

Responding to you question, no, I don't have any localhost running.

Thanks for your help.

**Comment by dewbjorn** [comment]
You're right, except that you only need to provide the directory of your localhost directory - so it should be `d:\xampp\htdocs\` instead of `d:\xampp\htdocs\index.html`. I now see that I could have made it clearer - sorry about that.

And yes, you should have a local server running in order for it work. I hope this helps :)

**Comment by ferrandusqui31** [comment]
Okay. I'm very grateful you helped me with that and you took you time. Now I inderstand this good. Thanks. :)
